### PR TITLE
update name to Deployer

### PR DESCRIPTION
**Pull request by timroster**
also minor markdown lint fixes

Signed-off-by: Tim Robinson <timroster@gmail.com>

### CODE REVIEW

**Comment by timroster** [comment]
@aairom - can we get this merged so I can add some extra documentation on Podman?

**Review by aairom — APPROVED** [review]

**Comment by aairom** [comment]
OKay

**Review by aairom — APPROVED** [review]

**Review by aairom — APPROVED** [review]

**Review by thomassuedbroecker — COMMENTED** [review]
This is only a naming change and have no impact on the automation.

**Comment by thomassuedbroecker** [comment]
Ok, we change the name.

**Pull request merged**
